### ISSUE TITLE
Project doesn't compile using VS community 2015

### ISSUE THREAD

**Issue by chrisdbc** [YuryStrozhevsky/C-plus-plus-ASN.1-2008-coder-decoder#1]
Thank you for posting this project.

However, the project doesn't compile (see below) and the file stage10.xslt seems to be missing.

Regards,

Chris

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		class "MSXML2::IXMLDOMElement" has no member "text"	compli_v2	c:\ZZZZ\C-plus-plus-ASN.1-2008-coder-decoder-master\C-plus-plus-ASN.1-2008-coder-decoder-master\code\main_file.cpp	210	
Error (active)		class "MSXML2::IXMLDOMDocument3" has no member "selectNodes"	compli_v2	c:\ZZZZ\C-plus-plus-ASN.1-2008-coder-decoder-master\C-plus-plus-ASN.1-2008-coder-decoder-master\code\main_file.cpp	187	
Error (active)		class "MSXML2::IXMLDOMElement" has no member "text"	compli_v2	c:\ZZZZ\C-plus-plus-ASN.1-2008-coder-decoder-master\C-plus-plus-ASN.1-2008-coder-decoder-master\code\main_file.cpp	204	
Error (active)		class "MSXML2::IXMLDOMElement" has no member "text"	compli_v2	c:\ZZZZ\C-plus-plus-ASN.1-2008-coder-decoder-master\C-plus-plus-ASN.1-2008-coder-decoder-master\code\main_file.cpp	221	
Error (active)		class "MSXML2::IXMLDOMElement" has no member "text"	compli_v2	c:\ZZZZ\C-plus-plus-ASN.1-2008-coder-decoder-master\C-plus-plus-ASN.1-2008-coder-decoder-master\code\main_file.cpp	227	
Error (active)		the default constructor of "utf8_conversion" cannot be referenced -- it is a deleted function	compli_v2	c:\ZZZZ\C-plus-plus-ASN.1-2008-coder-decoder-master\C-plus-plus-ASN.1-2008-coder-decoder-master\code\main_file.cpp	393	
Error (active)		class "MSXML2::IXMLDOMDocument3" has no member "transformNode"	compli_v2	c:\ZZZZ\C-plus-plus-ASN.1-2008-coder-decoder-master\C-plus-plus-ASN.1-2008-coder-decoder-master\code\main_file.cpp	394	
Error (active)		the default constructor of "utf8_conversion" cannot be referenced -- it is a deleted function	compli_v2	c:\ZZZZ\C-plus-plus-ASN.1-2008-coder-decoder-master\C-plus-plus-ASN.1-2008-coder-decoder-master\code\main_file.cpp	534	
Error (active)		class "MSXML2::IXMLDOMDocument3" has no member "transformNode"	compli_v2	c:\ZZZZ\C-plus-plus-ASN.1-2008-coder-decoder-master\C-plus-plus-ASN.1-2008-coder-decoder-master\code\main_file.cpp	535	
Error	RC2135	file not found: stage10.xslt	compli_v2	C:\ZZZZ\C-plus-plus-ASN.1-2008-coder-decoder-master\C-plus-plus-ASN.1-2008-coder-decoder-master\code\compli_v2.rc	54

**Comment by YuryStrozhevsky** [comment]
@chrisdbc Thanks, I will check it tomorrow.

**Comment by YuryStrozhevsky** [comment]
@chrisdbc I fixed the error with absence of stage10.xslt file. But I do not have errors with MSXML on my PC.   Please check that you did not change anything in solution settings and you do have MSXML 6 installed on your PC.
